#!/bin/zsh
set -e

DOTFILES="$HOME/.config/dotfiles"
movesuffix="moved-by-dotfiles-install"

function doit {
	printf "%s\n" "$*"
	"$@"
}

function link {
    readonly origin=$DOTFILES/${1:?"The origin must be specified."}
    target=${2:?"The target must be specified."}
    if [[ "${target##/home/}" == $target ]]; then
        target=$HOME/$target
    fi

    if [[ -L $target ]]; then
        linktarget=$(readlink -f $target)
        if [[ $linktarget == $origin ]]; then
            #echo "# already linked: $origin to $target"
        else
            doit mv $target $target.$movesuffix
            doit ln -s $origin $target
        fi
    elif [[ -f $target || -d $target ]]; then
        doit mv $target $target.$movesuffix
        doit ln -s $origin $target
    else
        parent=$(dirname "$target")
        if [[ ! -d $parent ]]; then
            doit mkdir -p $parent;
        fi
        doit ln -s $origin $target
    fi
}

function conflink {
    link $1 .config/$1
}

# Straightforward links
conflink gtk-3.0
conflink hypr
conflink jj
conflink kanshi
conflink kitty
conflink lsd
conflink mimeapps.list
conflink mutt/muttrc
conflink py3status
conflink ranger/rc.conf
conflink rofi/bin
conflink rofi/config
conflink rofi/themes
conflink sway
conflink swaync
conflink systemd
conflink tmux/tmux.conf
conflink vim/colors
conflink vim/vimrc
conflink waybar
conflink xdg-desktop-portal
conflink xdg-desktop-portal-wlr

# Nonstandard links
link git/gitconfig .config/git/config
link git/gitignore .gitignore
link mimeapps.list .local/share/applications/mimeapps.list
link user-dirs.dirs .config/user-dirs.dirs
link mutt/notmuch-mutt .local/bin/notmuch-mutt
link mutt/offlineimaprc .config/offlineimap/config
link notmuch/notmuch-config .notmuch-config
link picom/picom.conf .config/picom.conf
link rofi/rofi-pass.conf .config/rofi-pass/config
link rofi/rofimoji.rc .config/rofimoji.rc
link tig/tigrc .tigrc
link vim/vimrc .config/nvim/init.vim
link vim/coc-settings.json .config/nvim/coc-settings.json
link vim/colors/manuscript.vim /home/rixx/.local/share/nvim/plugged/vim-airline-themes/autoload/airline/themes/manuscript.vim
link X/XCompose .XCompose
link X/Xresources .Xresources
link X/xintitrc .xinitrc
link zsh/zshrc .zshrc

# Oh firefox. Why.
# First, check if there is a .mozilla directory.
if [[ -d $HOME/.mozilla ]]; then
    for profile in $HOME/.mozilla/firefox/*default*; do
        link firefox/userChrome.css $profile/chrome/userChrome.css;
    done
fi

# Some directories need to exist
mkdir -p ~/.local/share/zsh
