#!/bin/zsh
# This hook is sourced after every virtualenv is activated.
python -m pudb &> /dev/null

if [[ $? -eq 2 ]]; then
  export PYTHONBREAKPOINT="pudb.set_trace"
else
  export PYTHONBREAKPOINT=""
fi
