#!/bin/sh
#
# ~/.xinitrc
#

#For power saving: turn of screen after five minutes
xss-lock -- lock -n &
xautolock -time 10 -locker lock &

xset dpms 300 600 900 &
xset -b &
xset +fp /usr/share/fonts/local &
xset +fp $HOME/.local/share/fonts
xset fp rehash

#Background color
xsetroot -solid rgb:11/11/11

#Notifications
dunst &

#Compose
setxkbmap de nodeadkeys -option -option
setxkbmap -option compose:prsc

#auto-mounting
udiskie -t &

#copypasta
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

amixer sset Master 20%
amixer sset Master mute
amixer sset Capture nocap

export EDITOR=nvim
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

exec i3
