#!/bin/sh
#
# ~/.xinitrc

XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"

#For power saving: turn of screen after five minutes
xss-lock -- lock -n &
xautolock -time 10 -locker lock &

xset dpms 300 600 900 &
xset -b &
xset +fp /usr/share/fonts/local &
xset +fp $HOME/.local/share/fonts
xset fp rehash

#Fix trackpoint speed
xinput set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Speed" 1
xinput set-prop "pointer:Lite-On Technology Corp. ThinkPad USB Keyboard with TrackPoint" "libinput Accel Speed" 0

#Background color
xsetroot -solid rgb:11/11/11

#Notifications
dunst &

#Compose
setxkbmap de nodeadkeys -option -option
setxkbmap -option compose:prsc

#auto-mounting
udiskie -t &

#copypasta
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Mute and turn off microphone on start
amixer sset Master 50%
amixer sset Master mute
amixer sset Capture nocap

export EDITOR=nvim
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
export SSH_AUTH_SOCK

exec i3
