#!/bin/bash

SCREENSHOT_PATH=/home/rixx/tmp/screenshots/$(date --iso-8601=minutes).png

deepin-screenshot -s "$SCREENSHOT_PATH"

if [ -f "$SCREENSHOT_PATH" ]; then
    url=$(fb "$SCREENSHOT_PATH")
    notify-send "Uploaded $SCREENSHOT_PATH to $url"
fi
