# Theme
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

#############
# Variables #
#############

XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"

ZSH="$XDG_CONFIG_HOME/dotfiles/zsh"
if [[ -z "$ZSH_CACHE_DIR" ]]; then
  ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"
fi


fpath=($ZSH/modules $fpath)

plugins=(options completion aliases lib bgnotify colored-man git prompt ssh-agent title)

for file in $plugins; do
    source "$ZSH/modules/$file.zsh"
done

# Figure out the SHORT hostname
SHORT_HOST=${HOST/.*/}

# Load all stock functions (from $fpath files) called below.
autoload -U compaudit compinit

EDITOR=nvim

PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

PAGER=/usr/bin/less
LESSHISTFILE="$XDG_CACHE_DIR"/less/lesshist

alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR" 

export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export PASSWORD_STORE_KEY="7A2D8B7875486954"

WORKON_HOME=$XDG_DATA_HOME/virtualenvs
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
[ -s "/usr/bin/virtualenvwrapper.sh" ] && source /usr/bin/virtualenvwrapper.sh

if [[ ! $DISPLAY && $XDG_VTNR -le 3 ]]; then
	chmod +w ~
	exec startx
fi
