#############
# Variables #
#############

XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"

if [[ -z "$ZSH_CACHE_DIR" ]]; then
  ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"
fi

ZSH="$XDG_CONFIG_HOME/dotfiles/zsh"
fpath=($ZSH/modules $fpath)  # include functions from modules directory

plugins=(options completion aliases bgnotify colored-man git prompt ssh-agent tools fzf)

for file in $plugins; do
    source "$ZSH/modules/$file.zsh"
done

# Load all stock functions (from $fpath files) called below.
autoload -U compaudit

PATH="$HOME/.local/bin:$HOME/.config/dotfiles/bin:$PATH"

# If X is available and we're on one of the first 3 VTs, start X.
if [[ ! $DISPLAY && $XDG_VTNR -le 3 ]] && type startx > /dev/null; then
	chmod +w ~
	exec startx
fi
